// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package db

import (
	"context"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO project_domains (
    id, project_id, domain, target_port, enabled, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, domain, target_port, enabled, created_at, updated_at
`

type CreateDomainParams struct {
	ID         string `json:"id"`
	ProjectID  string `json:"project_id"`
	Domain     string `json:"domain"`
	TargetPort int64  `json:"target_port"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (ProjectDomain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.ID,
		arg.ProjectID,
		arg.Domain,
		arg.TargetPort,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProjectDomain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Domain,
		&i.TargetPort,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM project_domains WHERE id = ?
`

func (q *Queries) DeleteDomain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const deleteDomainsByProject = `-- name: DeleteDomainsByProject :exec
DELETE FROM project_domains WHERE project_id = ?
`

func (q *Queries) DeleteDomainsByProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteDomainsByProject, projectID)
	return err
}

const getDomain = `-- name: GetDomain :one
SELECT id, project_id, domain, target_port, enabled, created_at, updated_at FROM project_domains WHERE domain = ? LIMIT 1
`

func (q *Queries) GetDomain(ctx context.Context, domain string) (ProjectDomain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, domain)
	var i ProjectDomain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Domain,
		&i.TargetPort,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, project_id, domain, target_port, enabled, created_at, updated_at FROM project_domains ORDER BY created_at DESC
`

func (q *Queries) ListDomains(ctx context.Context) ([]ProjectDomain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectDomain{}
	for rows.Next() {
		var i ProjectDomain
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Domain,
			&i.TargetPort,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByProject = `-- name: ListDomainsByProject :many
SELECT id, project_id, domain, target_port, enabled, created_at, updated_at FROM project_domains WHERE project_id = ? ORDER BY created_at
`

func (q *Queries) ListDomainsByProject(ctx context.Context, projectID string) ([]ProjectDomain, error) {
	rows, err := q.db.QueryContext(ctx, listDomainsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectDomain{}
	for rows.Next() {
		var i ProjectDomain
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Domain,
			&i.TargetPort,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDomains = `-- name: ListEnabledDomains :many
SELECT id, project_id, domain, target_port, enabled, created_at, updated_at FROM project_domains WHERE enabled = 1 ORDER BY created_at DESC
`

func (q *Queries) ListEnabledDomains(ctx context.Context) ([]ProjectDomain, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectDomain{}
	for rows.Next() {
		var i ProjectDomain
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Domain,
			&i.TargetPort,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainEnabled = `-- name: SetDomainEnabled :exec
UPDATE project_domains SET enabled = ?, updated_at = ? WHERE id = ?
`

type SetDomainEnabledParams struct {
	Enabled   int64  `json:"enabled"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetDomainEnabled(ctx context.Context, arg SetDomainEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setDomainEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	return err
}

const updateDomainPort = `-- name: UpdateDomainPort :exec
UPDATE project_domains SET target_port = ?, updated_at = ? WHERE id = ?
`

type UpdateDomainPortParams struct {
	TargetPort int64  `json:"target_port"`
	UpdatedAt  string `json:"updated_at"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateDomainPort(ctx context.Context, arg UpdateDomainPortParams) error {
	_, err := q.db.ExecContext(ctx, updateDomainPort, arg.TargetPort, arg.UpdatedAt, arg.ID)
	return err
}
