// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT OR IGNORE INTO project_group_members (group_id, project_id) VALUES (?, ?)
`

type AddGroupMemberParams struct {
	GroupID   string `json:"group_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember, arg.GroupID, arg.ProjectID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO project_groups (id, name, sort_order, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, name, sort_order, created_at
`

type CreateGroupParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (ProjectGroup, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.CreatedAt,
	)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM project_groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT project_id FROM project_group_members WHERE group_id = ?
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var project_id string
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, sort_order, created_at FROM project_groups ORDER BY sort_order, created_at
`

func (q *Queries) ListGroups(ctx context.Context) ([]ProjectGroup, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectGroup{}
	for rows.Next() {
		var i ProjectGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM project_group_members WHERE group_id = ? AND project_id = ?
`

type RemoveGroupMemberParams struct {
	GroupID   string `json:"group_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.ProjectID)
	return err
}

const renameGroup = `-- name: RenameGroup :exec
UPDATE project_groups SET name = ? WHERE id = ?
`

type RenameGroupParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) error {
	_, err := q.db.ExecContext(ctx, renameGroup, arg.Name, arg.ID)
	return err
}
