// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Event struct {
	ID        int64  `json:"id"`
	ProjectID string `json:"project_id"`
	SessionID string `json:"session_id"`
	Ts        int64  `json:"ts"`
	Stream    string `json:"stream"`
	Text      string `json:"text"`
	Level     string `json:"level"`
	Source    string `json:"source"`
}

type MetricSample struct {
	ProjectID string  `json:"project_id"`
	Ts        int64   `json:"ts"`
	Status    string  `json:"status"`
	Port      int64   `json:"port"`
	Conns     int64   `json:"conns"`
	UptimeMs  int64   `json:"uptime_ms"`
	Attempts  int64   `json:"attempts"`
	ReqCount  int64   `json:"req_count"`
	ErrCount  int64   `json:"err_count"`
	P50Ms     int64   `json:"p50_ms"`
	P95Ms     int64   `json:"p95_ms"`
	P99Ms     int64   `json:"p99_ms"`
	BytesIn   int64   `json:"bytes_in"`
	BytesOut  int64   `json:"bytes_out"`
	HttpReqs  int64   `json:"http_reqs"`
	WsReqs    int64   `json:"ws_reqs"`
	MemKb     int64   `json:"mem_kb"`
	CpuPct    float64 `json:"cpu_pct"`
	Crashes   int64   `json:"crashes"`
	Autostops int64   `json:"autostops"`
	WakeMs    int64   `json:"wake_ms"`
}

type Project struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Path              string `json:"path"`
	Slug              string `json:"slug"`
	LocalDomain       string `json:"local_domain"`
	DetectedFramework string `json:"detected_framework"`
	PackageManager    string `json:"package_manager"`
	DevCommand        string `json:"dev_command"`
	DevPort           int64  `json:"dev_port"`
	Status            string `json:"status"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
	InstalledHash     string `json:"installed_hash"`
	Secure            int64  `json:"secure"`
	NodeVersion       string `json:"node_version"`
	RuntimeKind       string `json:"runtime_kind"`
	PhpVersion        string `json:"php_version"`
}

type ProjectDomain struct {
	ID         string `json:"id"`
	ProjectID  string `json:"project_id"`
	Domain     string `json:"domain"`
	TargetPort int64  `json:"target_port"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ProjectProcess struct {
	ID         string `json:"id"`
	ProjectID  string `json:"project_id"`
	Role       string `json:"role"`
	Kind       string `json:"kind"`
	WorkDir    string `json:"work_dir"`
	Command    string `json:"command"`
	Port       int64  `json:"port"`
	PhpVersion string `json:"php_version"`
	SortOrder  int64  `json:"sort_order"`
	CreatedAt  string `json:"created_at"`
}

type ProjectScript struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Command   string `json:"command"`
	CreatedAt string `json:"created_at"`
}

type ProjectService struct {
	ID         string `json:"id"`
	ProjectID  string `json:"project_id"`
	Engine     string `json:"engine"`
	Enabled    int64  `json:"enabled"`
	ConfigJson string `json:"config_json"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ServiceBinary struct {
	Engine      string `json:"engine"`
	Version     string `json:"version"`
	Path        string `json:"path"`
	Hash        string `json:"hash"`
	InstalledAt string `json:"installed_at"`
}
