// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Project struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Path              string `json:"path"`
	Slug              string `json:"slug"`
	LocalDomain       string `json:"local_domain"`
	DetectedFramework string `json:"detected_framework"`
	PackageManager    string `json:"package_manager"`
	DevCommand        string `json:"dev_command"`
	DevPort           int64  `json:"dev_port"`
	Status            string `json:"status"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type ProjectDomain struct {
	ID         string `json:"id"`
	ProjectID  string `json:"project_id"`
	Domain     string `json:"domain"`
	TargetPort int64  `json:"target_port"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ProjectScript struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Command   string `json:"command"`
	CreatedAt string `json:"created_at"`
}
