// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processes.sql

package db

import (
	"context"
)

const createProcess = `-- name: CreateProcess :one
INSERT INTO project_processes (
    id, project_id, role, kind, work_dir, command, port, php_version, sort_order, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, project_id, role, kind, work_dir, command, port, php_version, sort_order, created_at
`

type CreateProcessParams struct {
	ID         string `json:"id"`
	ProjectID  string `json:"project_id"`
	Role       string `json:"role"`
	Kind       string `json:"kind"`
	WorkDir    string `json:"work_dir"`
	Command    string `json:"command"`
	Port       int64  `json:"port"`
	PhpVersion string `json:"php_version"`
	SortOrder  int64  `json:"sort_order"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) CreateProcess(ctx context.Context, arg CreateProcessParams) (ProjectProcess, error) {
	row := q.db.QueryRowContext(ctx, createProcess,
		arg.ID,
		arg.ProjectID,
		arg.Role,
		arg.Kind,
		arg.WorkDir,
		arg.Command,
		arg.Port,
		arg.PhpVersion,
		arg.SortOrder,
		arg.CreatedAt,
	)
	var i ProjectProcess
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Role,
		&i.Kind,
		&i.WorkDir,
		&i.Command,
		&i.Port,
		&i.PhpVersion,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProcessesByProject = `-- name: DeleteProcessesByProject :exec
DELETE FROM project_processes WHERE project_id = ?
`

func (q *Queries) DeleteProcessesByProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteProcessesByProject, projectID)
	return err
}

const listProcessesByProject = `-- name: ListProcessesByProject :many
SELECT id, project_id, role, kind, work_dir, command, port, php_version, sort_order, created_at FROM project_processes WHERE project_id = ? ORDER BY sort_order
`

func (q *Queries) ListProcessesByProject(ctx context.Context, projectID string) ([]ProjectProcess, error) {
	rows, err := q.db.QueryContext(ctx, listProcessesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectProcess{}
	for rows.Next() {
		var i ProjectProcess
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Role,
			&i.Kind,
			&i.WorkDir,
			&i.Command,
			&i.Port,
			&i.PhpVersion,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
