// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id, name, path, slug, local_domain,
    detected_framework, package_manager, dev_command, dev_port,
    status, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
RETURNING id, name, path, slug, local_domain, detected_framework, package_manager, dev_command, dev_port, status, created_at, updated_at
`

type CreateProjectParams struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	Path              string `json:"path"`
	Slug              string `json:"slug"`
	LocalDomain       string `json:"local_domain"`
	DetectedFramework string `json:"detected_framework"`
	PackageManager    string `json:"package_manager"`
	DevCommand        string `json:"dev_command"`
	DevPort           int64  `json:"dev_port"`
	Status            string `json:"status"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Slug,
		arg.LocalDomain,
		arg.DetectedFramework,
		arg.PackageManager,
		arg.DevCommand,
		arg.DevPort,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Slug,
		&i.LocalDomain,
		&i.DetectedFramework,
		&i.PackageManager,
		&i.DevCommand,
		&i.DevPort,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, path, slug, local_domain, detected_framework, package_manager, dev_command, dev_port, status, created_at, updated_at FROM projects WHERE id = ? LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Slug,
		&i.LocalDomain,
		&i.DetectedFramework,
		&i.PackageManager,
		&i.DevCommand,
		&i.DevPort,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, path, slug, local_domain, detected_framework, package_manager, dev_command, dev_port, status, created_at, updated_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Slug,
			&i.LocalDomain,
			&i.DetectedFramework,
			&i.PackageManager,
			&i.DevCommand,
			&i.DevPort,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectStatus = `-- name: UpdateProjectStatus :exec
UPDATE projects SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateProjectStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
