// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scripts.sql

package db

import (
	"context"
)

const createScript = `-- name: CreateScript :one
INSERT INTO project_scripts (id, project_id, name, command, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, name, command, created_at
`

type CreateScriptParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Command   string `json:"command"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateScript(ctx context.Context, arg CreateScriptParams) (ProjectScript, error) {
	row := q.db.QueryRowContext(ctx, createScript,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Command,
		arg.CreatedAt,
	)
	var i ProjectScript
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Command,
		&i.CreatedAt,
	)
	return i, err
}

const listScriptsByProject = `-- name: ListScriptsByProject :many
SELECT id, project_id, name, command, created_at FROM project_scripts
WHERE project_id = ?
ORDER BY name
`

func (q *Queries) ListScriptsByProject(ctx context.Context, projectID string) ([]ProjectScript, error) {
	rows, err := q.db.QueryContext(ctx, listScriptsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectScript{}
	for rows.Next() {
		var i ProjectScript
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Command,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
